Repository cake-build/cake, pull requests merged in 2021-09, with the labels that each got.

#3435 setup useToolVersion override
  src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
  src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
  src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
  src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
  src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
  src/Cake.Common/Tools/MSBuild/MSBuildToolVersion.cs
  src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
Labels: Response from Cake team required

#3466 Fix two typos in GitReleaseManagerAliases documentation
  src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerAliases.cs
Labels: Documentation

#3446 GH2104: Added custom exit code to CakeException
  src/Cake.Cli/Infrastructure/ExceptionLogger.cs
  src/Cake.Core.Tests/Exceptions/CustomeExitCodeTests.cs
  src/Cake.Core/CakeException.cs
  src/Cake.Core/Tooling/Tool.cs
  src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
  src/Cake/Commands/DefaultCommand.cs
  src/Shared.msbuild
  tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
Labels: Waiting for issuer feedback
